document:
  name: LineeGuidaPagamenti_1_2
  description: |
    Le Linee guida perseguono l’obiettivo del legislatore di cogliere le opportunità offerte dalle nuove tecnologie per     facilitare le relazioni con i cittadini e le imprese. L’auspicato maggior utilizzo di strumenti di pagamento elettronici     facilita la messa a punto di processi fortemente automatizzati per la gestione e la riconciliazione dei pagamenti da     parte della Pubblica Amministrazione, nel rispetto delle soluzioni organizzative in essere. 
  tags:
    - SANP
    - pagoPA
    - LineeGuidaPagamenti
    - AgID
